### ISSUE TITLE
Resurrection Remix MM ROM bootloops if cache partition is wiped

### ISSUE THREAD

**Issue by gsstudios** [gsstudios/Dorimanx-SG2-I9100-Kernel#74]
Currently, Resurrection Remix users are not able to wipe cache partition because it can cause a bootloop. Not wiping cache partition avoids this issue, but it may be required at some point of time.

**Comment by Realex-fire** [comment]
kernel changes a set of parameters in build.prop and replaces system libraries.  For our kernel need the cleanup script.

**Comment by ssanjy** [comment]
Wiping cache affects booting of Beanstalk ROM too.

**Comment by dragonGR** [comment]
RR Mantainer here, how can i help?

**Comment by Realex-fire** [comment]
First of all we need boot logs (dmesg and logcat).
Ps: In the near future I will be busy and little than I will be able to help, but I will help as far as possible.

**Comment by questor** [comment]
I've seen this when wiping the cache and starting. Version used: Linux 3.15.0-Dorimanx-V13.0b004-N-SGII-SABER (but to be honest I've not used lineage-os, I'm using resurrection-remix; but kernel is working nice when I don't wipe the cache)
in dmesg I can see that the zygote is killed all the time:

```
<13>init: Service 'zygote' (pid 3156) killed by signal 9
<13>init: Service 'zygote' (pid 3156) killing any children in process group
<13>init: write_file: Unable to open '/sys/android_power/request_state': No such file or directory
<13>init: Service 'audioserver' is being killed...
<13>init: Service 'cameraserver' is being killed...
<13>init: Service 'media' is being killed...
<13>init: Service 'netd' is being killed...
<13>init: Service 'cameraserver' (pid 3065) killed by signal 9
<13>init: Service 'cameraserver' (pid 3065) killing any children in process group
<13>init: Starting service 'zygote'...
<13>init: Starting service 'cameraserver'...
<13>init: Service 'audioserver' (pid 3064) killed by signal 9
<13>init: Service 'audioserver' (pid 3064) killing any children in process group
<13>init: Service 'media' (pid 3101) killed by signal 9
<13>init: Service 'media' (pid 3101) killing any children in process group
<13>init: Service 'netd' (pid 3154) killed by signal 9
<13>init: Service 'netd' (pid 3154) killing any children in process group
<11>init: couldn't write 16753 to /dev/cpuset/camera-daemon/tasks: No such file or directory
<13>init: Starting service 'audioserver'...
<13>init: Starting service 'media'...
<13>init: Starting service 'netd'...
```

and in logcat I can see that the telephone-service is compiled:

```
08-23 05:14:10.652 16074 16087 W dex2oat : Compilation of boolean com.android.server.pm.Settings.readLPw(java.util.List) took 140.939ms
08-23 05:14:11.446 16074 16074 W dex2oat : Compilation of android.content.pm.PackageParser$Package com.android.server.pm.PackageManagerService.scanPackageDirtyLI(android.content.pm.PackageParser$Package, int, int, long, android.os.UserHandle) took 712.547ms
08-23 05:14:11.554 16074 16074 W dex2oat : Compilation of android.content.pm.PackageParser$Package com.android.server.pm.PackageManagerService.scanPackageInternalLI(android.content.pm.PackageParser$Package, java.io.File, int, int, long, android.os.UserHandle) took 107.875ms
08-23 05:14:12.848 16074 16074 W dex2oat : Compilation of void com.android.server.pm.PackageManagerService.dump(java.io.FileDescriptor, java.io.PrintWriter, java.lang.String[]) took 738.611ms
08-23 05:14:14.390 16074 16087 W dex2oat : Compilation of long com.android.server.policy.PhoneWindowManager.interceptKeyBeforeDispatching(android.view.WindowManagerPolicy$WindowState, android.view.KeyEvent, int) took 125.156ms
08-23 05:14:14.712 16074 16074 W dex2oat : Compilation of void com.android.server.power.PowerManagerService.dumpInternal(java.io.PrintWriter) took 207.725ms
08-23 05:14:16.264 16074 16087 W dex2oat : Compilation of void com.android.server.tv.TvInputManagerService$BinderService.dump(java.io.FileDescriptor, java.io.PrintWriter, java.lang.String[]) took 117.793ms
08-23 05:14:19.164 16074 16087 W dex2oat : Compilation of void com.android.server.wm.WindowManagerService$H.handleMessage(android.os.Message) took 161.528ms
08-23 05:14:19.629 16074 16074 W dex2oat : Compilation of int com.android.server.wm.WindowManagerService.addWindow(com.android.server.wm.Session, android.view.IWindow, int, android.view.WindowManager$LayoutParams, int, int, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.view.InputChannel) took 199.189ms
```


but when executing it's missing a class:

```
08-23 05:17:10.694 19216 19216 I SystemServer: InitWatchdog
08-23 05:17:10.695 19216 19216 I SystemServer: StartInputManagerService
08-23 05:17:10.696 19216 19216 I InputManager: Initializing input manager, mUseDevInputEventForAudioJack=false
08-23 05:17:10.699 19216 19216 I SystemServer: StartWindowManagerService
08-23 05:17:10.711 19216 19282 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.android.server.policy.PhoneWindowManager$4>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/internal/utils/du/DUSystemReceiver;
08-23 05:17:10.711 19216 19282 I art     :   at void com.android.server.wm.WindowManagerService.<init>(android.content.Context, com.android.server.input.InputManagerService, boolean, boolean, boolean) (WindowManagerService.java:402)
08-23 05:17:10.711 19216 19282 I art     :   at void com.android.server.wm.WindowManagerService.<init>(android.content.Context, com.android.server.input.InputManagerService, boolean, boolean, boolean, com.android.server.wm.WindowManagerService) (WindowManagerService.java:-1)
08-23 05:17:10.712 19216 19282 I art     :   at void com.android.server.wm.WindowManagerService$3.run() (WindowManagerService.java:951)
08-23 05:17:10.712 19216 19282 I art     :   at void android.os.Handler$BlockingRunnable.run() (Handler.java:771)
08-23 05:17:10.712 19216 19282 I art     :   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
08-23 05:17:10.712 19216 19282 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
08-23 05:17:10.712 19216 19282 I art     :   at void android.os.Looper.loop() (Looper.java:154)
08-23 05:17:10.712 19216 19282 I art     :   at void android.os.HandlerThread.run() (HandlerThread.java:61)
08-23 05:17:10.712 19216 19282 I art     :   at void com.android.server.ServiceThread.run() (ServiceThread.java:46)
08-23 05:17:10.712 19216 19282 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.utils.du.DUSystemReceiver" on path: DexPathList[[zip file "/system/framework/org.cyanogenmod.platform.jar", zip file "/system/framework/org.cyanogenmod.hardware.jar", zip file "/system/framework/services.jar", zip file "/system/framework/ethernet-service.jar", zip file "/system/framework/wifi-service.jar"],nativeLibraryDirectories=[/system/lib, /vendor/lib, /system/lib, /vendor/lib]]
08-23 05:17:10.712 19216 19282 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
08-23 05:17:10.712 19216 19282 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
08-23 05:17:10.712 19216 19282 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
08-23 05:17:10.712 19216 19282 I art     :   at void com.android.server.wm.WindowManagerService.<init>(android.content.Context, com.android.server.input.InputManagerService, boolean, boolean, boolean) (WindowManagerService.java:402)
08-23 05:17:10.712 19216 19282 I art     :   at void com.android.server.wm.WindowManagerService.<init>(android.content.Context, com.android.server.input.InputManagerService, boolean, boolean, boolean, com.android.server.wm.WindowManagerService) (WindowManagerService.java:-1)
08-23 05:17:10.712 19216 19282 I art     :   at void com.android.server.wm.WindowManagerService$3.run() (WindowManagerService.java:951)
08-23 05:17:10.712 19216 19282 I art     :   at void android.os.Handler$BlockingRunnable.run() (Handler.java:771)
08-23 05:17:10.712 19216 19282 I art     :   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
08-23 05:17:10.712 19216 19282 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
08-23 05:17:10.712 19216 19282 I art     :   at void android.os.Looper.loop() (Looper.java:154)
08-23 05:17:10.712 19216 19282 I art     :   at void android.os.HandlerThread.run() (HandlerThread.java:61)
08-23 05:17:10.712 19216 19282 I art     :   at void com.android.server.ServiceThread.run() (ServiceThread.java:46)
08-23 05:17:10.712 19216 19282 I art     : 
08-23 05:17:10.783 19216 19282 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.android.server.policy.PhoneWindowManager$4>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/internal/utils/du/DUSystemReceiver;
08-23 05:17:10.783 19216 19282 I art     :   at void com.android.server.wm.WindowManagerService.<init>(android.content.Context, com.android.server.input.InputManagerService, boolean, boolean, boolean) (WindowManagerService.java:402)
08-23 05:17:10.783 19216 19282 I art     :   at void com.android.server.wm.WindowManagerService.<init>(android.content.Context, com.android.server.input.InputManagerService, boolean, boolean, boolean, com.android.server.wm.WindowManagerService) (WindowManagerService.java:-1)
08-23 05:17:10.783 19216 19282 I art     :   at void com.android.server.wm.WindowManagerService$3.run() (WindowManagerService.java:951)
08-23 05:17:10.783 19216 19282 I art     :   at void android.os.Handler$BlockingRunnable.run() (Handler.java:771)
08-23 05:17:10.783 19216 19282 I art     :   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
08-23 05:17:10.783 19216 19282 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
08-23 05:17:10.783 19216 19282 I art     :   at void android.os.Looper.loop() (Looper.java:154)
08-23 05:17:10.783 19216 19282 I art     :   at void android.os.HandlerThread.run() (HandlerThread.java:61)
08-23 05:17:10.783 19216 19282 I art     :   at void com.android.server.ServiceThread.run() (ServiceThread.java:46)
08-23 05:17:10.783 19216 19282 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.utils.du.DUSystemReceiver" on path: DexPathList[[zip file "/system/framework/org.cyanogenmod.platform.jar", zip file "/system/framework/org.cyanogenmod.hardware.jar", zip file "/system/framework/services.jar", zip file "/system/framework/ethernet-service.jar", zip file "/system/framework/wifi-service.jar"],nativeLibraryDirectories=[/system/lib, /vendor/lib, /system/lib, /vendor/lib]]
08-23 05:17:10.783 19216 19282 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
08-23 05:17:10.783 19216 19282 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
08-23 05:17:10.783 19216 19282 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
08-23 05:17:10.783 19216 19282 I art     :   at void com.android.server.wm.WindowManagerService.<init>(android.content.Context, com.android.server.input.InputManagerService, boolean, boolean, boolean) (WindowManagerService.java:402)
08-23 05:17:10.783 19216 19282 I art     :   at void com.android.server.wm.WindowManagerService.<init>(android.content.Context, com.android.server.input.InputManagerService, boolean, boolean, boolean, com.android.server.wm.WindowManagerService) (WindowManagerService.java:-1)
08-23 05:17:10.783 19216 19282 I art     :   at void com.android.server.wm.WindowManagerService$3.run() (WindowManagerService.java:951)
08-23 05:17:10.783 19216 19282 I art     :   at void android.os.Handler$BlockingRunnable.run() (Handler.java:771)
08-23 05:17:10.783 19216 19282 I art     :   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
08-23 05:17:10.783 19216 19282 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
08-23 05:17:10.783 19216 19282 I art     :   at void android.os.Looper.loop() (Looper.java:154)
08-23 05:17:10.783 19216 19282 I art     :   at void android.os.HandlerThread.run() (HandlerThread.java:61)
08-23 05:17:10.783 19216 19282 I art     :   at void com.android.server.ServiceThread.run() (ServiceThread.java:46)
08-23 05:17:10.783 19216 19282 I art     : 
08-23 05:17:10.784 19216 19216 E System  : ******************************************
08-23 05:17:10.785 19216 19216 E System  : ************ Failure starting core service
08-23 05:17:10.785 19216 19216 E System  : java.lang.SecurityException
08-23 05:17:10.785 19216 19216 E System  : 	at android.os.BinderProxy.transactNative(Native Method)
08-23 05:17:10.785 19216 19216 E System  : 	at android.os.BinderProxy.transact(Binder.java:615)
08-23 05:17:10.785 19216 19216 E System  : 	at android.os.ServiceManagerProxy.addService(ServiceManagerNative.java:150)
08-23 05:17:10.785 19216 19216 E System  : 	at android.os.ServiceManager.addService(ServiceManager.java:72)
08-23 05:17:10.785 19216 19216 E System  : 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:693)
08-23 05:17:10.785 19216 19216 E System  : 	at com.android.server.SystemServer.run(SystemServer.java:372)
08-23 05:17:10.785 19216 19216 E System  : 	at com.android.server.SystemServer.main(SystemServer.java:241)
08-23 05:17:10.785 19216 19216 E System  : 	at java.lang.reflect.Method.invoke(Native Method)
08-23 05:17:10.785 19216 19216 E System  : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
08-23 05:17:10.785 19216 19216 E System  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
08-23 05:17:10.785 19216 19216 I SystemServiceManager: Starting com.android.server.InputMethodManagerService$Lifecycle
08-23 05:17:10.788 19216 19282 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.display
08-23 05:17:10.788 19216 19282 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/internal/utils/du/DUSystemReceiver;
08-23 05:17:10.788 19216 19282 E AndroidRuntime: 	at com.android.server.wm.WindowManagerService.<init>(WindowManagerService.java:402)
08-23 05:17:10.788 19216 19282 E AndroidRuntime: 	at com.android.server.wm.WindowManagerService.<init>(WindowManagerService.java)
08-23 05:17:10.788 19216 19282 E AndroidRuntime: 	at com.android.server.wm.WindowManagerService$3.run(WindowManagerService.java:951)
08-23 05:17:10.788 19216 19282 E AndroidRuntime: 	at android.os.Handler$BlockingRunnable.run(Handler.java:771)
08-23 05:17:10.788 19216 19282 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
08-23 05:17:10.788 19216 19282 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-23 05:17:10.788 19216 19282 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
08-23 05:17:10.788 19216 19282 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
08-23 05:17:10.788 19216 19282 E AndroidRuntime: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
08-23 05:17:10.788 19216 19282 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.utils.du.DUSystemReceiver" on path: DexPathList[[zip file "/system/framework/org.cyanogenmod.platform.jar", zip file "/system/framework/org.cyanogenmod.hardware.jar", zip file "/system/framework/services.jar", zip file "/system/framework/ethernet-service.jar", zip file "/system/framework/wifi-service.jar"],nativeLibraryDirectories=[/system/lib, /vendor/lib, /system/lib, /vendor/lib]]
08-23 05:17:10.788 19216 19282 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
08-23 05:17:10.788 19216 19282 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
08-23 05:17:10.788 19216 19282 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-23 05:17:10.788 19216 19282 E AndroidRuntime: 	... 9 more
08-23 05:17:10.792 19216 19282 I Process : Sending signal. PID: 19216 SIG: 9
08-23 05:17:10.844  3075  3075 E         : eof
08-23 05:17:10.844  3075  3075 E         : failed to read size
08-23 05:17:10.844  3075  3075 I         : closing connection
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'package' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'otadexopt' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'user' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'activity' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'procstats' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'meminfo' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'gfxinfo' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'dbinfo' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'cpuinfo' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'permission' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'processinfo' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'overlay' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'battery' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'usagestats' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'webviewupdate' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'scheduling_policy' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'telephony.registry' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'media.camera.proxy' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'account' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'content' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'vibrator' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'consumer_ir' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'alarm' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'batterystats' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'appops' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'power' died
08-23 05:17:10.845  3033  3033 I ServiceManager: service 'display' died
08-23 05:17:10.845  3032  3032 I lowmemorykiller: ActivityManager disconnected
08-23 05:17:10.846  3032  3032 I lowmemorykiller: Closing Activity Manager data connection
08-23 05:17:10.887 18931 18931 E Zygote  : Exit zygote because system server (19216) has terminated
```

**Comment by questor** [comment]
@dragonGR any idea why a kernel-change triggers this? my guess is that some security stuff is wrong with this kernel, but I have no idea what exactly (the package is available on the device).
